# action.yml
name: 'Packagaya GitHub Action'
description: 'Runs Packagaya on your repository to analyze the issues in the code.'
runs:
    using: 'composite'
    steps:
        - run: yarn global add @packagaya/cli
          shell: bash
        - run: yarn add -D -W @packagaya/ts-adapter
          shell: bash
        - run: packagaya sync info
          shell: bash
